export const FIRST_CHARACTER = 0;

export const MIN_USERNAME_CHARACTERS = 1;
export const MAX_USERNAME_CHARACTERS = 32;

export const MIN_USER_EMAIL_CHARACTERS = 1;
export const MAX_USER_EMAIL_CHARACTERS = 48;

export const MIN_USER_PASSWORD_CHARACTERS = 8;
export const MAX_USER_PASSWORD_CHARACTERS = 32;

export const MIN_DEVICE_NAME_CHARACTERS = 1;
export const MAX_DEVICE_NAME_CHARACTERS = 32;

export const MIN_DEVICE_SECRET_CHARACTERS = 0;
export const MAX_DEVICE_SECRET_CHARACTERS = 32;

export const MIN_DEVICE_VIEWING_SECRET_CHARACTERS = 0;
export const MAX_DEVICE_VIEWING_SECRET_CHARACTERS = 32;

export const MAX_DEVICE_ID_CHARACTERS = 16;

export const HEX_PER_BYTE = 2;

export const GENERATED_USER_RAW_SALT_BYTES = 16;
export const USER_SALT_AS_STRING_BYTES = GENERATED_USER_RAW_SALT_BYTES * HEX_PER_BYTE;

export const DEVICE_SECRET_RAW_SALT_BYTES = 16;
export const DEVICE_SECRET_SALT_AS_STRING_BYTES = DEVICE_SECRET_RAW_SALT_BYTES * HEX_PER_BYTE;

export const DEVICE_VIEWING_SECRET_RAW_SALT_BYTES = 16;
export const DEVICE_VIEWING_SECRET_SALT_AS_STRING_BYTES = DEVICE_VIEWING_SECRET_RAW_SALT_BYTES * HEX_PER_BYTE;

export const SHA512_OUTPUT_RAW_BYTES = 64;
export const SHA512_AS_STRING_BYTES = SHA512_OUTPUT_RAW_BYTES * HEX_PER_BYTE;

export const UUID_RAW_BYTES = 16;
export const UUID_DASHES = 4;
export const UUID_CHARACTER_COUNT = (UUID_RAW_BYTES * HEX_PER_BYTE) + UUID_DASHES;

export const HTTP_STATUS_FOR_OK = 200;
export const HTTP_STATUS_FOR_CREATED = 201;
export const HTTP_STATUS_FOR_BAD_REQUEST = 400; 
export const HTTP_STATUS_FOR_UNAUTHORIZED = 401;
export const HTTP_STATUS_FOR_SERVER_ERROR = 500;